const Integration = {
  NA: null,
  INTEGRATED: true,
  NOT_INTEGRATED: false
}

export const notes = ({
  family_notes: "", // (TextField)
  history_notes: "", // (TextField)
  goals_notes: "", // (TextField)
  school_and_therapy_notes: "", // (TextField)
  medical_notes: "", // (TextField)
  physiology_notes: "", // (TextField)
  edbs_notes: "", // (TextField)
  daily_activities_notes: "", // (TextField)
  tactility_channel_notes: "", // (TextField)
  auditory_channel_notes: "", // (TextField)
  visual_channel_notes: "", // (TextField)
  sensitivities_notes: "", // (TextField)
  manual_channel_notes: "", // (TextField)
  language_channel_notes: "", // (TextField)
  whole_brain_lang_notes: "", // (TextField)
  mobility_channel_notes: "" // (TextField)
})

export const reflex = ({
  moro_reflex_comment: "",  // (TextField)
  moro_reflex: Integration.NA, // (Integration)
  spinal_galant_reflex_comment: "",  // (TextField)
  spinal_galant_reflex: Integration.NA, // (Integration)
  crossed_extensor_reflex_comment: "",  // (TextField)
  crossed_extensor_reflex: Integration.NA, // (Integration)
  spinal_perez_reflex_comment: "",  // (TextField)
  spinal_perez_reflex: Integration.NA, // (Integration)
  babinski_reflex_comment: "",  // (TextField)
  babinski_reflex: Integration.NA, // (Integration)
  asymmetrical_tonic_neck_reflex_comment: "",  // (TextField)
  asymmetrical_tonic_neck_reflex: Integration.NA, // (Integration)
  bauer_crawling_reflex_comment: "",  // (TextField)
  bauer_crawling_reflex: Integration.NA, // (Integration)
  babkin_palmomental_reflex_comment: "",  // (TextField)
  babkin_palmomental_reflex: Integration.NA, // (Integration)
  hand_grasping_reflex_comment: "",  // (TextField)
  hand_grasping_reflex: Integration.NA, // (Integration)
  frontal_release_comment: "",  // (TextField)
  frontal_release_snout: Integration.NA, // (Integration)
  frontal_release_sucking: Integration.NA, // (Integration)
  frontal_release_rooting: Integration.NA, // (Integration)
  frontal_release_glabellar: Integration.NA, // (Integration)
  stepping_reflex_comment: "",  // (TextField)
  stepping_reflex: Integration.NA, // (Integration)
  hands_pulling_reflex_comment: "",  // (TextField)
  hands_pulling_reflex: Integration.NA, // (Integration)
  hands_supporting_reflex_comment: "",  // (TextField)
  hands_supporting_reflex_left: Integration.NA, // (Integration)
  hands_supporting_reflex_right: Integration.NA, // (Integration)
  landau_reflex_comment: "",  // (TextField)
  landau_reflex: Integration.NA, // (Integration)
})

export const tactility = ({
  deep_pressure_comment: "", // (TextField)
  deep_pressure: null, // (ChannelScore)
  tonicity_comment: "", // (TextField)
  tonicity_face: null, // (ChannelScore)
  tonicity_neck: null, // (ChannelScore)
  tonicity_trunk: null, // (ChannelScore)
  tonicity_shoulder_right: null, // (ChannelScore)
  tonicity_shoulder_left: null, // (ChannelScore)
  tonicity_arm_right: null, // (ChannelScore)
  tonicity_arm_left: null, // (ChannelScore)
  tonicity_hand_right: null, // (ChannelScore)
  tonicity_hand_left: null, // (ChannelScore)
  tonicity_hip_right: null, // (ChannelScore)
  tonicity_hip_left: null, // (ChannelScore)
  tonicity_leg_right: null, // (ChannelScore)
  tonicity_leg_left: null, // (ChannelScore)
  tonicity_foot_right: null, // (ChannelScore)
  tonicity_foot_left: null, // (ChannelScore)
  deep_pain_reaction_commen: "", //t(TextField)
  deep_pain_reaction: null, // (ChannelScore)
  surface_touch_comment: "", // (TextField)
  surface_touch_hand_right: null, // (ChannelScore)
  surface_touch_hand_left: null, // (ChannelScore)
  surface_touch_foot_right: null, // (ChannelScore)
  surface_touch_foot_left: null, // (ChannelScore)
  surface_pain_reaction_comment: "", // (TextField)
  surface_pain_reaction: null, // (ChannelScore)
  olfactory_stimulation_comment: "", // (TextField)
  olfactory_stimulation_strong: null, // (ChannelScore)
  olfactory_stimulation_sweet: null, // (ChannelScore)
  facial_surface_awareness_comment: "", // (TextField)
  facial_surface_awareness: null, // (ChannelScore)
  oral_textural_awareness_comment: "", // (TextField)
  oral_textural_awareness_mushy: null, // (ChannelScore)
  oral_textural_awareness_crunchy: null, // (ChannelScore)
  page_discrimination_comment: "", // (TextField)
  page_discrimination_cardboard: null, // (NegativeChannelScore)
  page_discrimination_paper: null, // (NegativeChannelScore)
  tactile_discrimination_medium_comment: "", // (TextField)
  tactile_discrimination_medium_visual: null, // (NegativeChannelScore)
  tactile_discrimination_medium_nonvisual: null, // (NegativeChannelScore)
  tactile_discrimination_small_comment: "", // (TextField)
  tactile_discrimination_small_visual: null, // (NegativeChannelScore)
  tactile_discrimination_small_nonvisual: null, // (NegativeChannelScore)
  rhomberg_comment: "", // (TextField)
  rhomberg_eyes_open: null, // (NegativeChannelScore)
  rhomberg_eyes_closed: null, // (NegativeChannelScore)
  manns_right_foot_comment: "", // (TextField)
  manns_right_foot_eyes_open: null, // (NegativeChannelScore)
  manns_right_foot_eyes_closed: null, // (NegativeChannelScore)
  manns_left_foot_comment: "", // (TextField)
  manns_left_foot_eyes_open: null, // (NegativeChannelScore)
  manns_left_foot_eyes_closed: null, // (NegativeChannelScore)
  arm_matching_comment: "", // (TextField)
  arm_matching_front: null, // (NegativeChannelScore)
  arm_matching_above: null, // (NegativeChannelScore)
  arm_matching_sides: null, // (NegativeChannelScore)
  graphesthesia_comment: "", // (TextField)
  graphesthesia_right: null, // (NegativeChannelScore)
  graphesthesia_left: null, // (NegativeChannelScore)
})

export const auditory = () => ({
  vestibular_function_comment:"", // (TextField)
  vestibular_function_right: null, // (ChannelScore)
  vestibular_function_left: null, // (ChannelScore)
  threatening_sound_reaction_comment: null, // (ChannelScore)
  threatening_sound_reaction: null, // (ChannelScore)
  sound_sensitivity_comment:"", // (TextField)
  sound_sensitivity: null, // (ChannelScore)
  tonality_change_reaction_comment:"", // (TextField)
  receptive_words_comment:"", // (TextField)
  receptive_words: null, // (NegativeChannelScore)
  one_step_directions_comment:"", // (TextField)
  one_step_directions: null, // (NegativeChannelScore)
  two_word_phrases_comment:"", // (TextField)
  two_word_phrases: null, // (NegativeChannelScore)
  sentence_understanding_comment:"", // (TextField)
  sentence_understanding: null, // (NegativeChannelScore)
  auditory_processing_speed_comment:"", // (TextField)
  auditory_processing_speed_one: null, // (NegativeChannelScore)
  auditory_processing_speed_two: null, // (NegativeChannelScore)
  auditory_processing_speed_three: null, // (NegativeChannelScore)
  auditory_processing_speed_four: null, // (NegativeChannelScore)
})

export const visual = () => ({
  tracking_horizontal_comment: "", // (TextField)
  tracking_horizontal: null, // (ChannelScore)
  tracking_vertical_comment: "", // (TextField)
  tracking_vertical: null, // (ChannelScore)
  convergence_comment: "", // (TextField)
  convergence: null, // (ChannelScore)
  divergence_comment: "", // (TextField)
  divergence: null, // (ChannelScore)
  eight_tracking_horizontal_comment: "", // (TextField)
  eight_tracking_horizontal: null, // (ChannelScore)
  eight_tracking_vertical_comment: "", // (TextField)
  eight_tracking_vertical: null, // (ChannelScore)
  eight_tracking_con_div_comment: "", // (TextField)
  eight_tracking_con_div: null, // (ChannelScore)
  do_these_comment: "", // (TextField)
  do_these_comment: null, // (ChannelScore)
  initial_match_colors_comment: "", // (TextField)
  initial_match_colors: null, // (ChannelScore)
  initial_match_shapes_comment: "", // (TextField)
  initial_match_shapes: null, // (ChannelScore)
  initial_match_pic_comment: "", // (TextField)
  initial_match_pic: null, // (ChannelScore)
  colors_comment: "", // (TextField)
  colors: null, // (NegativeChannelScore)
  shapes_comment: "", // (TextField)
  shapes: null, // (NegativeChannelScore)
  numbers_comment: "", // (TextField)
  numbers: null, // (NegativeChannelScore)
  uppercase_letters_comment: "", // (TextField)
  uppercase_letters: null, // (NegativeChannelScore)
  lowercase_letters_comment: "", // (TextField)
  lowercase_letters: null, // (NegativeChannelScore)
  initial_sight_words_comment: "", // (TextField)
  initial_sight_words: null, // (NegativeChannelScore)
  visual_processing_speed_comment: "", // (TextField)
  visual_processing_speed: null, // (NegativeChannelScore)
})

export const language = () => ({
  sound_verbal_response_comment: "", // (TextField)
  sound_verbal_response: null, // (NegativeChannelScore)
  lip_utilization_comment: "", // (TextField)
  lip_utilization: null, // (NegativeChannelScore)
  oral_motor_movement_comment: "", // (TextField)
  oral_motor_movement: null, // (NegativeChannelScore)
  breath_support_comment: "", // (TextField)
  breath_support: null, // (NegativeChannelScore)
  phonation_comment: "", // (TextField)
  phonation: null, // (NegativeChannelScore)
  vowel_production_short_comment: "", // (TextField)
  vowel_production_short: null, // (NegativeChannelScore)
  vowel_production_long_comment: "", // (TextField)
  vowel_production_long: null, // (NegativeChannelScore)
  vowel_consonant_production_comment: "", // (TextField)
  vowel_consonant_production: null, // (NegativeChannelScore)
  meaningful_tone_use_comment: "", // (TextField)
  meaningful_tone_use: null, // (NegativeChannelScore)
  identify_pic_receptively_comment: "", // (TextField)
  identify_pic_receptively_fo2: null, // (NegativeChannelScore)
  identify_pic_receptively_fo3: null, // (NegativeChannelScore)
  identify_pic_receptively_comment: "", // (TextField)
  identify_pic_expressively_v1: null, // (NegativeChannelScore)
  identify_pic_expressively_v2: null, // (NegativeChannelScore)
  identify_pic_expressively_v3: null, // (NegativeChannelScore)
  articulation_initial_comment: "", // (TextField)
  articulation_initial: null, // (NegativeChannelScore)
  articulation_medial_comment: "", // (TextField)
  articulation_medial: null, // (NegativeChannelScore)
  articulation_final_comment: "", // (TextField)
  articulation_final: null, // (NegativeChannelScore)
  spontaneous_verbalizations_comment: "", // (TextField)
  spontaneous_verbalizations: null, // (NegativeChannelScore)
  yes_no_response_comment: "", // (TextField)
  yes_no_response: null, // (NegativeChannelScore)
  phrases_comment: "", // (TextField)
  phrases_response: null, // (NegativeChannelScore)
  sentences_response_comment: "", // (TextField)
  sentences_response: null, // (NegativeChannelScore)
  conversation_exchange_comment: "", // (TextField)
  conversation_exchange: null, // (NegativeChannelScore)
  opposites_comment: "", // (TextField)
  opposites: null, // (NegativeChannelScore)
})

export const mobility = () => ({
  forearm_prop_comment: "", // (TextField)
  forearm_prop: null, // (NegativeChannelScore)
  belly_rotations_comment: "", // (TextField)
  belly_rotations_right: null, // (NegativeChannelScore)
  belly_rotations_left: null, // (NegativeChannelScore)
  belly_crawl_comment: "", // (TextField)
  belly_crawl: null, // (NegativeChannelScore)
  prone_to_cat_comment: "", // (TextField)
  prone_to_cat: null, // (NegativeChannelScore)
  momentary_sit_comment: "", // (TextField)
  momentary_sit: null, // (NegativeChannelScore)
  move_upright_sit_comment: "", // (TextField)
  move_upright_sit: null, // (NegativeChannelScore)
  pull_to_feet_comment: "", // (TextField)
  pull_to_feet: null, // (NegativeChannelScore)
  hold_creep_comment: "", // (TextField)
  hold_creep: null, // (NegativeChannelScore)
  creep_comment: "", // (TextField)
  creep: null, // (NegativeChannelScore)
  sit_to_stand_comment: "", // (TextField)
  sit_to_stand: null, // (NegativeChannelScore)
  standing_comment: "", // (TextField)
  standing: null, // (NegativeChannelScore)
  protective_response_comment: "", // (TextField)
  protective_response: null, // (NegativeChannelScore)
  walks_comment: "", // (TextField)
  walks: null, // (NegativeChannelScore)
  gait_comment: "", // (TextField)
  gait: null, // (NegativeChannelScore)
  march_initial_comment: "", // (TextField)
  march_initial: null, // (NegativeChannelScore)
  kick_stationary_ball_comment: "", // (TextField)
  kick_stationary_ball: null, // (NegativeChannelScore)
  cross_march_comment: "", // (TextField)
  cross_march: null, // (NegativeChannelScore)
  run_comment: "", // (TextField)
  run: null, // (NegativeChannelScore)
  throw_ball_medium_comment: "", // (TextField)
  throw_ball_medium: null, // (NegativeChannelScore)
  throw_ball_small_comment: "", // (TextField)
  throw_ball_small: null, // (NegativeChannelScore)
  catch_ball_medium_comment: "", // (TextField)
  catch_ball_medium: null, // (NegativeChannelScore)
  jump_object_comment: "", // (TextField)
  jump_object: null, // (NegativeChannelScore)
  balance_eyes_open_comment: "", // (TextField)
  balance_eyes_open_right: null, // (NegativeChannelScore)
  balance_eyes_open_left: null, // (NegativeChannelScore)
  balance_eyes_closed_comment: "", // (TextField)
  balance_eyes_closed_right: null, // (NegativeChannelScore)
  balance_eyes_closed_left: null, // (NegativeChannelScore)
  one_foot_hop_comment: "", // (TextField)
  one_foot_hop_right: null, // (NegativeChannelScore)
  one_foot_hop_left: null, // (NegativeChannelScore)
  stairs_comment: "", // (TextField)
  stairs_up: null, // (NegativeChannelScore)
  stairs_down: null, // (NegativeChannelScore)
  walks_arms_cross_comment: "", // (TextField)
  walks_arms_cross: null, // (NegativeChannelScore)
  initial_skip_comment: "", // (TextField)
  initial_skip: null, // (NegativeChannelScore)
  cross_skip_comment: "", // (TextField)
  cross_skip: null, // (NegativeChannelScore)
  jumping_jacks_comment: "", // (TextField)
  jumping_jacks: null, // (NegativeChannelScore)
  four_piece_cross_comment: "", // (TextField)
  four_piece_cross: null, // (NegativeChannelScore)
})

export const sensory = () => ({
  hands_comment: "", // (TextField)
  hands: null, // (PositiveChannelScore)
  feet_comment: "", // (TextField)
  feet: null, // (PositiveChannelScore)
  trunk_comment: "", // (TextField)
  trunk: null, // (PositiveChannelScore)
  jaw_comment: "", // (TextField)
  jaw: null, // (PositiveChannelScore)
  intraoral_comment: "", // (TextField)
  intraoral: null, // (PositiveChannelScore)
  extraoral_comment: "", // (TextField)
  extraoral: null, // (PositiveChannelScore)
  chin_comment: "", // (TextField)
  chin: null, // (PositiveChannelScore)
  genitals_comment: "", // (TextField)
  genitals: null, // (PositiveChannelScore)
  olfactory_comment: "", // (TextField)
  olfactory: null, // (PositiveChannelScore)
  jumping_comment: "", // (TextField)
  jumping: null, // (PositiveChannelScore)
  vocal_vibration_comment: "", // (TextField)
  vocal_vibration: null, // (PositiveChannelScore)
  humming_comment: "", // (TextField)
  humming: null, // (PositiveChannelScore)
  plug_ear_comment: "", // (TextField)
  plug_ear_right: null, // (PositiveChannelScore)
  plug_ear_left: null, // (PositiveChannelScore)
  spinning_comment: "", // (TextField)
  spinning_right: null, // (PositiveChannelScore)
  spinning_left: null, // (PositiveChannelScore)
  singing_comment: "", // (TextField)
  singing: null, // (PositiveChannelScore)
  rocking_comment: "", // (TextField)
  rocking: null, // (PositiveChannelScore)
  pressure_comment: "", // (TextField)
  pressure: null, // (PositiveChannelScore)
  finger_play_comment: "", // (TextField)
  finger_play: null, // (PositiveChannelScore)
  corner_vision_comment: "", // (TextField)
  corner_vision: null, // (PositiveChannelScore)
  object_edges_comment: "", // (TextField)
  object_edges: null, // (PositiveChannelScore)
  spinning_objects_comment: "", // (TextField)
  spinning_objects: null, // (PositiveChannelScore)
  hold_straight_object_comment: "", // (TextField)
  hold_straight_object: null, // (PositiveChannelScore)
  shadows_comment: "", // (TextField)
  shadows: null, // (PositiveChannelScore)
})

export const sensitivity = () => ({
  haircuts_comment: "", // (TextArea)
  haircuts:null, // (PositiveChannelScore)
  washing_face_comment: "", // (TextArea)
  washing_face:null, // (PositiveChannelScore)
  washing_hair_comment: "", // (TextArea)
  washing_hair:null, // (PositiveChannelScore)
  brushing_teeth_comment: "", // (TextArea)
  brushing_teeth:null, // (PositiveChannelScore)
  nail_cutting_comment: "", // (TextArea)
  nail_cutting_fingers:null, // (PositiveChannelScore)
  nail_cutting_toes:null, // (PositiveChannelScore)
  tags_comment: "", // (TextArea)
  tags:null, // (PositiveChannelScore)
  shirt_comment: "", // (TextArea)
  shirt:null, // (PositiveChannelScore)
  pants_comment: "", // (TextArea)
  pants:null, // (PositiveChannelScore)
  socks_comment: "", // (TextArea)
  socks:null, // (PositiveChannelScore)
  shoes_comment: "", // (TextArea)
  shoes:null, // (PositiveChannelScore)
  coat_comment: "", // (TextArea)
  coat:null, // (PositiveChannelScore)
})
